# 20240821
# Bryony J Leeke, phD
# MRC LMS 


# Smarca4 senescence project
# IMR90 siRNA data resequenced PE150

# locus level analyis


# libraries

# libraries
library(DESeq2)
library(tidyverse)
library(lubridate)
library(pheatmap)
library(RColorBrewer)
library(ashr)
library(ggrepel)


# directories
data_dir <- "/home/bleeke/mnt/network/chrom_dev/chrom_dev/+ANALYSIS/Michelle/367_250819_4OHT_siSMARCA4/counts/"
plot_dir <- "/home/bleeke/mnt/network/chrom_dev/chrom_dev/+ANALYSIS/Michelle/367_250819_4OHT_siSMARCA4/plots/BJL/"
dir.create(plot_dir)
metadata_dir <-"/home/bleeke/mnt/network/chrom_dev/chrom_dev/+ANALYSIS/Michelle/367_250819_4OHT_siSMARCA4/"
output_dir <- "/home/bleeke/mnt/network/chrom_dev/chrom_dev/+ANALYSIS/Michelle/367_250819_4OHT_siSMARCA4/BJL_outputs/"
dir.create(output_dir)


# import metadata
setwd(metadata_dir)
metadata_df <- read_delim("metadata2.txt") %>%
  mutate(Condition = as.factor(Condition)) %>%
  filter(Vee == "Y") # remove samples that Vee said are questionable


# counts file generated by Michelle
# import locus level TE count data
count_data <- read.delim(paste0(data_dir, "2024-08-20_teloci_counts_raw_filtered_renamed.txt")) %>%
  select(metadata_df$SampleID)

# remove rows with low counts. 6 samples chosen as this is the number of repeat per condition
count_data <- count_data[rowSums(count_data >0) >= 5, ]

# DESeq object
dds_te_loci <- count_data %>%
  as.matrix() %>%
  DESeqDataSetFromMatrix(colData=metadata_df,design = ~ 0)
dds_te_loci <- estimateSizeFactors(dds_te_loci)

#vst normalise
vsd_te_loci <- vst(dds_te_loci)

# correlation heatmap
anno <- as.data.frame(colData(vsd_te_loci)) %>% select(Condition) # metadata
vsd_te_loci_mat <- assay(vsd_te_loci)
vsd_te_loci_cor <- cor(vsd_te_loci_mat) 
pdf(paste0(plot_dir, today(), "_TE_loci_vsd_correlation_heatmap.pdf"))
pheatmap(vsd_te_loci_cor, annotation = anno, show_colnames=TRUE, show_rownames = FALSE )
dev.off()

# sample distances clustering
sampleDists <- dist(t(assay(vsd_te_loci)))

sampleDistMatrix <- as.matrix(sampleDists)
#rownames(sampleDistMatrix) <- paste0(vsd_te_loci$Condition, "_", colnames(vsd_te_loci))
#colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")))(255)
pdf(paste0(plot_dir, today(), "_TE_loci_vsd_Euclid_distance_heatmap.pdf"))
pheatmap(sampleDistMatrix,
         clustering_distance_rows = sampleDists,
         clustering_distance_cols = sampleDists,
         col = colors)
dev.off()

# PCA
PCA_data <- plotPCA(vsd_te_loci, intgroup = "Condition", returnData=TRUE)
percentVar <- round(100 * attr(PCA_data, "percentVar"))
PCA_data %>%
  mutate(Condition = factor(Condition, levels = c("siNT_DMSO", "siNT_4OHT", "siSMARCA4_4OHT"))) %>%
ggplot(aes(PC1, PC2, colour=Condition)) +
  geom_point(size=4) +
  #geom_label_repel(aes(label = name), position = "nudge")+
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  scale_color_manual(values = c("siNT_4OHT" = "#08bc3c", "siNT_DMSO" =  "#ff706c", "siSMARCA4_4OHT" = "#689cfc"))
ggsave(paste0(plot_dir, today(), "_TE_loci_vsd_PCA_1_2.pdf"), width = 10, height = 10)



# differential expression analysis
design(dds_te_loci) = ~ Condition
dds_te_loci <- DESeq(dds_te_loci)

# save dds object
saveRDS(dds_te_loci, file = paste0(output_dir, today(), "_dds_te_loci.RDS"))

# what are the names of the results
resultsNames(dds_te_loci)

# get results for contrast of interest "Condition_siSMARCA4_4OHT_vs_siNT_4OHT"
res_condition_siSMARCA4_4OHT_vs_siNT_4OHT <- results(dds_te_loci, alpha = 0.05, contrast = c("Condition", "siSMARCA4_4OHT", "siNT_4OHT"))

# shrink results 
res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT <- lfcShrink(dds_te_loci, type="ashr", coef = "Condition_siSMARCA4_4OHT_vs_siNT_4OHT")

# define TE classes to subset data by for plotting (manually)
classes <-c("DNA", "LINE", "LTR", "SINE", "Satellite", "Retroposon", "srpRNA", "scRNA", "RC", "Unknown")


# reorganise l2FC data to dataframe and save


results_tb <- res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT %>%
  data.frame() %>%
  rownames_to_column(var="feature_ID") %>% 
  separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]")

results_tb_sig <- res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT %>%
  data.frame() %>%
  rownames_to_column(var="feature_ID") %>% 
  separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]") %>%
  filter(padj <=0.05)

write_delim(results_tb, paste0(output_dir, "L2FC_repeat_loci_siSMARCA4_4OHT_vs_siNT_4OHT.txt"), delim = "\t")
write_delim(results_tb_sig, paste0(output_dir, "L2FC_repeat_loci_siSMARCA4_4OHT_vs_siNT_4OHT_padj_0.05.txt"), delim = "\t")

# sig per class



for(i in 1:length(classes)){
  
  plot_dat <- res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT [grepl(classes[i], rownames(res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT)),] 
  
  
  # MA plot
  pdf(paste0(plot_dir, today(), "_", classes[i], "_TE_loci_MA_alpha_0_05.pdf"))
  plotMA(plot_dat, alpha = 0.05, ylim=c(-4,4), 
         main = " MA plot, alpha = 0.05", ylab = "log fold change siSMARCA4_4OHT vs siNT_4OHT ")
  dev.off()
  
  # volcano plot - subset by TE family/loci  
  
  results_tb <- plot_dat %>%
    data.frame() %>%
    rownames_to_column(var="feature_ID") %>% 
    separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]") %>%
    unite(feature_ID, class_family, subfamily, sep = "_") %>%
    mutate(threshold_OE = abs(padj) <= 0.05) %>% # logical vector where TRUE values denote padj values <= 0.05
    mutate(genelabels = case_when(threshold_OE == TRUE & abs(log2FoldChange) >1.5 ~ feature_ID)) # and to label these on the plot
  
  
  # volcano plot
  ggplot(results_tb, aes(x = log2FoldChange, y = -log10(padj))) +
    geom_point(aes(colour = threshold_OE)) +
    geom_label_repel(aes(label = genelabels), max.overlaps = Inf) +
    ggtitle("siSMARCA4_4OHT vs siNT_4OHT") +
    xlab("log2 fold change") + 
    ylab("-log10 adjusted p-value") +
    #xlim(-4,4)+
    theme_bw()+
    theme(legend.position = "none",
          plot.title = element_text(size = rel(1.5), hjust = 0.5),
          axis.title = element_text(size = rel(1.25))) 
  
  ggsave(paste0(plot_dir, today(), "_", classes[i], "_TE_loci_volcano_absL2FC_1.5.pdf"), width = 5, height = 10) 
  
}




# volcano of all repeats

results_tb <- res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT %>%
  data.frame() %>%
  rownames_to_column(var="feature_ID") %>% 
  separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]") %>%
  unite(feature_ID, class_family, subfamily, sep = "_") %>%
  mutate(threshold_OE = abs(padj) <= 0.05) %>% # logical vector where TRUE values denote padj values <= 0.05
  mutate(genelabels = case_when(threshold_OE == TRUE & abs(log2FoldChange) >2.5 ~ feature_ID)) # and to label these on the plot


# volcano plot
ggplot(results_tb, aes(x = log2FoldChange, y = -log10(padj))) +
  geom_point(aes(colour = threshold_OE)) +
  geom_label_repel(aes(label = genelabels), max.overlaps = Inf) +
  ggtitle("siSMARCA4_4OHT vs siNT_4OHT") +
  xlab("log2 fold change") + 
  ylab("-log10 adjusted p-value") +
  #xlim(-4,4)+
  theme_bw()+
  theme(legend.position = "none",
        plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = rel(1.25))) 

ggsave(paste0(plot_dir, today(), "_TE_loci_volcano_label_absL2FC_2.5.pdf"), width = 5, height = 10) 


results_tb <- res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT %>%
  data.frame() %>%
  rownames_to_column(var="feature_ID") %>% 
  separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]") %>%
  unite(feature_ID, class_family, subfamily, sep = "_") %>%
  mutate(threshold_OE = abs(padj) <= 0.05) %>% # logical vector where TRUE values denote padj values <= 0.05
  mutate(genelabels = case_when(threshold_OE == TRUE & log2FoldChange >1 ~ feature_ID)) # and to label these on the plot


# volcano plot
ggplot(results_tb, aes(x = log2FoldChange, y = -log10(padj))) +
  geom_point(aes(colour = threshold_OE)) +
  geom_label_repel(aes(label = genelabels), max.overlaps = Inf) +
  ggtitle("siSMARCA4_4OHT vs siNT_4OHT") +
  xlab("log2 fold change") + 
  ylab("-log10 adjusted p-value") +
  #xlim(-4,4)+
  theme_bw()+
  theme(legend.position = "none",
        plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = rel(1.25))) 

ggsave(paste0(plot_dir, today(), "_TE_loci_volcano_label_L2FC_up1.pdf"), width = 5, height = 10) 


results_tb <- res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT %>%
  data.frame() %>%
  rownames_to_column(var="feature_ID") %>% 
  separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]") %>%
  unite(feature_ID, class_family, subfamily, sep = "_") %>%
  mutate(threshold_OE = abs(padj) <= 0.05) %>% # logical vector where TRUE values denote padj values <= 0.05
  mutate(genelabels = case_when(threshold_OE == TRUE & log2FoldChange >1.5 ~ feature_ID)) # and to label these on the plot


# volcano plot
ggplot(results_tb, aes(x = log2FoldChange, y = -log10(padj))) +
  geom_point(aes(colour = threshold_OE)) +
  geom_label_repel(aes(label = genelabels), max.overlaps = Inf) +
  ggtitle("siSMARCA4_4OHT vs siNT_4OHT") +
  xlab("log2 fold change") + 
  ylab("-log10 adjusted p-value") +
  #xlim(-4,4)+
  theme_bw()+
  theme(legend.position = "none",
        plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = rel(1.25))) 

ggsave(paste0(plot_dir, today(), "_TE_loci_volcano_label_L2FC_up1.5.pdf"), width = 5, height = 10) 


# boxplots L2FC

# boxplots 

tmp <- res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT %>%
  as.data.frame()%>%
  rownames_to_column("feature_ID") %>%
  separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]") %>%
  select(subfamily) %>%
  unique()


#L1s
L1PA_label <- tmp[grepl("L1PA", tmp$subfamily),]

plot_data <- res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT %>%
  as.data.frame()%>%
  rownames_to_column("feature_ID") %>%
  separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]") %>%
  filter(class_family == "LINE/L1") %>%
  mutate(group = case_when(subfamily == "L1HS" ~ "L1HS",
                           subfamily %in% L1PA_label ~ "L1PA",
                           is.character(subfamily) ~ "all_L1"))

plot_data %>%
  ggplot(aes(x = group,
             y = log2FoldChange))+
  geom_boxplot(outliers=F)+
  theme_bw()+
  ylab("log2FC siSMARCA4_4OHT vs siNT_4OHT")
ggsave(paste0(plot_dir, today(), "boxplot_l2fc_siSMARCA4_4OHT_vs_siNT_4OHT_L1HS_L1PA_all_no_outliers.pdf"))

plot_data %>%
  ggplot(aes(x = group,
             y = log2FoldChange))+
  geom_boxplot(outliers=T)+
  theme_bw()+
  ylab("log2FC siSMARCA4_4OHT vs siNT_4OHT")
ggsave(paste0(plot_dir, today(), "boxplot_l2fc_siSMARCA4_4OHT_vs_siNT_4OHT_L1HS_L1PA_all.pdf"))

# l2FC boxplot for MER92-int vs all LTRs

tmp <- res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT %>%
  as.data.frame()%>%
  rownames_to_column("feature_ID") %>%
  separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]")

LTRs_label <- unique(tmp$class_family)[grep("LTR", unique(tmp$class_family))]

plot_data <- res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT %>%
  as.data.frame()%>%
  rownames_to_column("feature_ID") %>%
  separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]") %>%
  filter(class_family %in% LTRs_label) %>%
  mutate(group = case_when(subfamily == "MER92-int" ~ "MER92-int",
                           is.character(subfamily) ~ "all_LTR"))

plot_data %>%
  ggplot(aes(x = group,
             y = log2FoldChange))+
  geom_boxplot(outliers=T)+
  theme_bw()+
  ylab("log2FC siSMARCA4_4OHT vs siNT_4OHT")
ggsave(paste0(plot_dir, today(), "boxplot_l2fc_siSMARCA4_4OHT_vs_siNT_4OHT_MER92-int_all_LTRs.pdf"))


plot_data %>%
  ggplot(aes(x = group,
             y = log2FoldChange))+
  geom_boxplot(outliers=F)+
  theme_bw()+
  ylab("log2FC siSMARCA4_4OHT vs siNT_4OHT")
ggsave(paste0(plot_dir, today(), "boxplot_l2fc_siSMARCA4_4OHT_vs_siNT_4OHT_MER92-int_all_LTRs_no_outliers.pdf"))

# l2fc boxplot for satellites

satellites_label <- c("Satellite/centr", "Satellite/subtelo", "Satellite/acro","Satellite")

plot_data <- res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT %>%
  as.data.frame()%>%
  rownames_to_column("feature_ID") %>%
  separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]") %>%
  filter(class_family %in% satellites_label)

plot_data %>%
  ggplot(aes(x = class_family,
             y = log2FoldChange))+
  geom_boxplot(outliers=T)+
  theme_bw()+
  ylab("log2FC siSMARCA4_4OHT vs siNT_4OHT")
ggsave(paste0(plot_dir, today(), "boxplot_l2fc_siSMARCA4_4OHT_vs_siNT_4OHT_satellites.pdf"))


plot_data %>%
  ggplot(aes(x = class_family,
             y = log2FoldChange))+
  geom_boxplot(outliers=F)+
  theme_bw()+
  ylab("log2FC siSMARCA4_4OHT vs siNT_4OHT")
ggsave(paste0(plot_dir, today(), "boxplot_l2fc_siSMARCA4_4OHT_vs_siNT_4OHT_satellites_no_outliers.pdf"))


plot_data %>%
  ggplot(aes(x = subfamily,
             y = log2FoldChange,
             fill = class_family))+
  geom_boxplot(outliers=T)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylab("log2FC siSMARCA4_4OHT vs siNT_4OHT")
ggsave(paste0(plot_dir, today(), "boxplot_l2fc_siSMARCA4_4OHT_vs_siNT_4OHT_satellites_subfamily.pdf"), width = 20)


# L2FC boxplot all elements grouped by class_family

plot_data <- res_shrunk_condition_siSMARCA4_4OHT_vs_siNT_4OHT %>%
  as.data.frame()%>%
  rownames_to_column("feature_ID") %>%
  separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]")

plot_data %>%
  ggplot(aes(x = class_family,
             y = log2FoldChange))+
  geom_boxplot(outliers=T)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylab("log2FC siSMARCA4_4OHT vs siNT_4OHT")
ggsave(paste0(plot_dir, today(), "boxplot_l2fc_siSMARCA4_4OHT_vs_siNT_4OHT_all_class_family.pdf"), width =20)


plot_data %>%
  ggplot(aes(x = class_family,
             y = log2FoldChange))+
  geom_boxplot(outliers=F)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylab("log2FC siSMARCA4_4OHT vs siNT_4OHT")
ggsave(paste0(plot_dir, today(), "boxplot_l2fc_siSMARCA4_4OHT_vs_siNT_4OHT_all_class_family_no_outliers.pdf"), width =20)



# normalised_counts boxplots
normalised_counts <- counts(dds_te_loci, normalized=T) %>% 
  as.data.frame() %>%
  rownames_to_column(var="feature_ID") %>%
  separate(feature_ID, into = c("class_family", "subfamily", "chromosome", "start", "end"), sep = "[|]") %>%
  pivot_longer(!c("class_family", "subfamily", "chromosome", "start", "end"),
               names_to = "sample",
               values_to = "normalised_count") %>%
  mutate(Condition = case_when(sample %in% metadata_df$SampleID[metadata_df$Condition == "siNT_4OHT"] ~ "siNT_4OHT",
                               sample %in% metadata_df$SampleID[metadata_df$Condition == "siSMARCA4_4OHT"] ~ "siSMARCA4_4OHT",
                               sample %in% metadata_df$SampleID[metadata_df$Condition == "siNT_DMSO"] ~ "siNT_DMSO"))

# for L1
plot_dat <- normalised_counts %>% 
  filter(class_family == "LINE/L1") %>%
  group_by(Condition, chromosome, start, end, class_family,subfamily) %>%
  summarise(mean = mean(normalised_count)) %>%
  mutate(group = case_when(subfamily == "L1HS" ~ "L1HS",
                           subfamily %in% L1PA_label ~ "L1PA",
                           is.character(subfamily) ~ "all_L1")) %>%
  mutate(condition = factor(Condition, levels = c("siNT_DMSO", "siNT_4OHT","siSMARCA4_4OHT")))

plot_dat %>%
  ggplot(aes(x = group,
             y = log2(mean+1),
             fill = condition))+
  geom_boxplot(outliers=T)+
  theme_bw()+
  ylab("log2(normalised counts + 1)")
ggsave(paste0(plot_dir, today(), "boxplot_normalised_counts_L1HS_L1PA_all.pdf"))

# for satellites

satellites_label <- c("Satellite/centr", "Satellite/subtelo", "Satellite/acro","Satellite")

plot_dat <- normalised_counts %>% 
  filter(class_family %in% satellites_label) %>%
  group_by(Condition, chromosome, start, end, class_family,subfamily) %>%
  summarise(mean = mean(normalised_count)) %>%
  mutate(condition = factor(Condition, levels = c("siNT_DMSO", "siNT_4OHT","siSMARCA4_4OHT")))

plot_dat %>%
  ggplot(aes(x = class_family,
             y = log2(mean+1),
             fill = condition))+
  geom_boxplot(outliers=T)+
  theme_bw()+
  ylab("log2(normalised counts + 1)")
ggsave(paste0(plot_dir, today(), "boxplot_normalised_counts_satellites.pdf"))

plot_dat %>%
  ggplot(aes(x = class_family,
             y = log2(mean+1),
             fill = condition))+
  geom_boxplot(outliers=F)+
  theme_bw()+
  ylab("log2(normalised counts + 1)")
ggsave(paste0(plot_dir, today(), "boxplot_normalised_counts_satellites_no_outliers.pdf"))

# for MER92-int vs all LTRs

plot_dat <- normalised_counts %>% 
  filter(class_family %in% LTRs_label) %>%
  group_by(Condition, chromosome, start, end, class_family,subfamily) %>%
  summarise(mean = mean(normalised_count)) %>%
  mutate(condition = factor(Condition, levels = c("siNT_DMSO", "siNT_4OHT","siSMARCA4_4OHT"))) %>%
  mutate(group = case_when(subfamily == "MER92-int" ~ "MER92-int",
                           is.character(subfamily) ~ "all_LTR"))

plot_dat %>%
  ggplot(aes(x = group,
             y = log2(mean+1),
             fill = condition))+
  geom_boxplot(outliers=T)+
  theme_bw()+
  ylab("log2(normalised counts + 1)")
ggsave(paste0(plot_dir, today(), "boxplot_normalised_counts_MER92-int_all_LTRs.pdf"))

plot_dat %>%
  ggplot(aes(x = group,
             y = log2(mean+1),
             fill = condition))+
  geom_boxplot(outliers=F)+
  theme_bw()+
  ylab("log2(normalised counts + 1)")
ggsave(paste0(plot_dir, today(), "boxplot_normalised_counts_MER92-int_all_LTRs_no_outliers.pdf"))


# all
plot_dat <- normalised_counts %>% 
  group_by(Condition, chromosome, start, end, class_family,subfamily) %>%
  summarise(mean = mean(normalised_count)) %>%
  mutate(condition = factor(Condition, levels = c("siNT_DMSO", "siNT_4OHT","siSMARCA4_4OHT")))

# split by class/family
plot_dat %>%
  ggplot(aes(x = class_family,
             y = log2(mean+1),
             fill = condition))+
  geom_boxplot(outliers=T)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylab("log2(normalised counts + 1)")
ggsave(paste0(plot_dir, today(), "boxplot_normalised_counts_all_repeats_class_subfamily.pdf"), width = 20)


# split by class/family no outliers
plot_dat %>%
  ggplot(aes(x = class_family,
             y = log2(mean+1),
             fill = condition))+
  geom_boxplot(outliers=F)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylab("log2(normalised counts + 1)")
ggsave(paste0(plot_dir, today(), "boxplot_normalised_counts_all_repeats_class_subfamily_no_outliers.pdf"), width = 20)



# not split by class/family
plot_dat %>%
  ggplot(aes(x = condition,
             y = log2(mean+1),
             fill = condition))+
  geom_boxplot(outliers=T)+
  theme_bw()+
  ylab("log2(normalised counts + 1)")

ggsave(paste0(plot_dir, today(), "boxplot_normalised_counts_all_repeats.pdf"))



# not split by class/family no outliers
plot_dat %>%
  ggplot(aes(x = condition,
             y = log2(mean+1),
             fill = condition))+
  geom_boxplot(outliers=F)+
  theme_bw()+
  ylab("log2(normalised counts + 1)")

ggsave(paste0(plot_dir, today(), "boxplot_normalised_counts_all_repeats_no_outliers.pdf"))

# normalised counts boxplot for SINES


SINEs_label <- unique(tmp$class_family)[grep("SINE", unique(tmp$class_family))]

plot_dat <- normalised_counts %>% 
  filter(class_family %in% SINEs_label) %>%
  group_by(Condition, chromosome, start, end, class_family,subfamily) %>%
  summarise(mean = mean(normalised_count)) %>%
  mutate(condition = factor(Condition, levels = c("siNT_DMSO", "siNT_4OHT","siSMARCA4_4OHT")))

plot_dat %>%
  ggplot(aes(x = class_family,
             y = log2(mean+1),
             fill = condition))+
  geom_boxplot(outliers=T)+
  theme_bw()+
  ylab("log2(normalised counts + 1)")
ggsave(paste0(plot_dir, today(), "boxplot_normalised_counts_SINEs.pdf"))

plot_dat %>%
  ggplot(aes(x = class_family,
             y = log2(mean+1),
             fill = condition))+
  geom_boxplot(outliers=F)+
  theme_bw()+
  ylab("log2(normalised counts + 1)")
ggsave(paste0(plot_dir, today(), "boxplot_normalised_counts_SINEs_no_outliers.pdf"))


